# Generated by Django 3.2.6 on 2021-08-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19India',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('state_union_territory', models.CharField(max_length=100)),
                ('confirmed_indian_national', models.IntegerField(null=True)),
                ('confirmed_foreign_national', models.IntegerField(null=True)),
                ('cured', models.IntegerField(null=True)),
                ('deaths', models.IntegerField(null=True)),
                ('confirmed', models.IntegerField(null=True)),
            ],
        ),
    ]
