# Generated by Django 3.2.6 on 2021-08-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidVaccineStatewise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('total_doses_administered', models.IntegerField(null=True)),
                ('total_sessions_conducted', models.IntegerField(null=True)),
                ('total_sites', models.IntegerField(null=True)),
                ('first_dose_administered', models.IntegerField(null=True)),
                ('second_dose_administered', models.IntegerField(null=True)),
                ('male_vaccinated', models.IntegerField(null=True)),
                ('female_vaccinated', models.IntegerField(null=True)),
                ('transgender_vaccinated', models.IntegerField(null=True)),
                ('total_covaxin_administered', models.IntegerField(null=True)),
                ('total_coviShield_administered', models.IntegerField(null=True)),
                ('total_sputnik5_administered', models.IntegerField(null=True)),
                ('aefi', models.IntegerField(null=True)),
                ('age_18_45', models.IntegerField(null=True)),
                ('age_45_60', models.IntegerField(null=True)),
                ('age_60_plus', models.IntegerField(null=True)),
                ('total_individuals_vaccinated', models.IntegerField(null=True)),
            ],
        ),
    ]
