name: Deploy to PythonAnywhere

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Reload PythonAnywhere Web App
              run: |
                  curl --header 'Authorization: Token ${{ secrets.PYTHON_ANYWHERE_API_TOKEN }}' --request POST \
                  https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHON_ANYWHERE_USERNAME }}/webapps/${{ secrets.PYTHON_ANYWHERE_DOMAIN_NAME }}/reload/
